[package]
name = "libkfr-sys"
version = "0.1.0"
authors = ["ninja0x0"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54.1"
pkg-config = "0.3.7"
cmake = "0.1.44"

[dependencies]
